version: "3.9"
volumes:
  data:
services:
  bot:
    build:
      context: .
      dockerfile: Bot/Dockerfile
    container_name: Bot
    restart: unless-stopped
    environment:
        - TOKEN
        - DATABASE=server=localhost;port=3306;uid=root;pwd=root;database=bot
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: supersecurepassword
      MYSQL_DATABASE: bot
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"
