version: "3.9"
services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_USER: 'bot'
      MARIADB_PASSWORD: 'supersecurepassword'
      MARIADB_DATABASE: 'bot'
      MARIADB_ROOT_PASSWORD: 'supersecurepassword'
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - "3310:3306"


  bot:
    build:
      context: .
      dockerfile: Bot/Dockerfile
    container_name: Bot
    restart: unless-stopped
    environment:
      - TOKEN
      - DATABASE=server=db;port=3306;user=bot;password=supersecurepassword;database=bot
    depends_on:
      - db
    command: sh -c "dotnet ef database update --no-build && dotnet run --no-build --project Bot"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: bot
      PMA_PASSWORD: supersecurepassword
    ports:
      - "8080:80"


volumes:
  mariadb-data:
    name: 'template-mariadb-data'
