version: "3.9"
services:
    postgres:
        container_name: 'houston-postgres'
        image: postgres:15
        volumes:
            - postgres:/var/lib/postgresql/data
        restart: unless-stopped
        environment:
            POSTGRES_USER: 'houston'
            POSTGRES_PASSWORD: 'supersecurepassword'
            POSTGRES_DB: 'houston'
            
    bot:
        container_name: 'houston-bot'
        build:
            context: './src'
            dockerfile: 'Houston.Bot/Dockerfile'
        depends_on:
            - postgres
        volumes:
            - './bot-logs:/app/logs'
        restart: unless-stopped
        environment:
            - TOKEN=${TOKEN}
            - DATABASE=Server=postgres;Port=5432;Database=houston;UserId=houston;Password=supersecurepassword;
        env_file:
          - .env
        logging:
            driver: "local"
            options:
                max-size: 50M

volumes:
    postgres: